package com.quranmedia.player.wear.domain.model

/**
 * Lightweight surah metadata for fast index loading.
 * Contains only the info needed for the index screen - no verses.
 */
data class SurahInfo(
    val id: Int,
    val name: String,
    val transliteration: String,
    val type: String,
    val totalVerses: Int
)

/**
 * Pre-defined surah metadata for instant index loading.
 * This avoids loading the entire Quran JSON just to show the surah list.
 */
object SurahMetadata {
    val all: List<SurahInfo> = listOf(
        SurahInfo(1, "الفاتحة", "Al-Fatiha", "Meccan", 7),
        SurahInfo(2, "البقرة", "Al-Baqara", "Medinan", 286),
        SurahInfo(3, "آل عمران", "Aal-Imran", "Medinan", 200),
        SurahInfo(4, "النساء", "An-Nisa", "Medinan", 176),
        SurahInfo(5, "المائدة", "Al-Ma'ida", "Medinan", 120),
        SurahInfo(6, "الأنعام", "Al-An'am", "Meccan", 165),
        SurahInfo(7, "الأعراف", "Al-A'raf", "Meccan", 206),
        SurahInfo(8, "الأنفال", "Al-Anfal", "Medinan", 75),
        SurahInfo(9, "التوبة", "At-Tawba", "Medinan", 129),
        SurahInfo(10, "يونس", "Yunus", "Meccan", 109),
        SurahInfo(11, "هود", "Hud", "Meccan", 123),
        SurahInfo(12, "يوسف", "Yusuf", "Meccan", 111),
        SurahInfo(13, "الرعد", "Ar-Ra'd", "Medinan", 43),
        SurahInfo(14, "إبراهيم", "Ibrahim", "Meccan", 52),
        SurahInfo(15, "الحجر", "Al-Hijr", "Meccan", 99),
        SurahInfo(16, "النحل", "An-Nahl", "Meccan", 128),
        SurahInfo(17, "الإسراء", "Al-Isra", "Meccan", 111),
        SurahInfo(18, "الكهف", "Al-Kahf", "Meccan", 110),
        SurahInfo(19, "مريم", "Maryam", "Meccan", 98),
        SurahInfo(20, "طه", "Ta-Ha", "Meccan", 135),
        SurahInfo(21, "الأنبياء", "Al-Anbiya", "Meccan", 112),
        SurahInfo(22, "الحج", "Al-Hajj", "Medinan", 78),
        SurahInfo(23, "المؤمنون", "Al-Mu'minun", "Meccan", 118),
        SurahInfo(24, "النور", "An-Nur", "Medinan", 64),
        SurahInfo(25, "الفرقان", "Al-Furqan", "Meccan", 77),
        SurahInfo(26, "الشعراء", "Ash-Shu'ara", "Meccan", 227),
        SurahInfo(27, "النمل", "An-Naml", "Meccan", 93),
        SurahInfo(28, "القصص", "Al-Qasas", "Meccan", 88),
        SurahInfo(29, "العنكبوت", "Al-Ankabut", "Meccan", 69),
        SurahInfo(30, "الروم", "Ar-Rum", "Meccan", 60),
        SurahInfo(31, "لقمان", "Luqman", "Meccan", 34),
        SurahInfo(32, "السجدة", "As-Sajda", "Meccan", 30),
        SurahInfo(33, "الأحزاب", "Al-Ahzab", "Medinan", 73),
        SurahInfo(34, "سبأ", "Saba", "Meccan", 54),
        SurahInfo(35, "فاطر", "Fatir", "Meccan", 45),
        SurahInfo(36, "يس", "Ya-Sin", "Meccan", 83),
        SurahInfo(37, "الصافات", "As-Saffat", "Meccan", 182),
        SurahInfo(38, "ص", "Sad", "Meccan", 88),
        SurahInfo(39, "الزمر", "Az-Zumar", "Meccan", 75),
        SurahInfo(40, "غافر", "Ghafir", "Meccan", 85),
        SurahInfo(41, "فصلت", "Fussilat", "Meccan", 54),
        SurahInfo(42, "الشورى", "Ash-Shura", "Meccan", 53),
        SurahInfo(43, "الزخرف", "Az-Zukhruf", "Meccan", 89),
        SurahInfo(44, "الدخان", "Ad-Dukhan", "Meccan", 59),
        SurahInfo(45, "الجاثية", "Al-Jathiya", "Meccan", 37),
        SurahInfo(46, "الأحقاف", "Al-Ahqaf", "Meccan", 35),
        SurahInfo(47, "محمد", "Muhammad", "Medinan", 38),
        SurahInfo(48, "الفتح", "Al-Fath", "Medinan", 29),
        SurahInfo(49, "الحجرات", "Al-Hujurat", "Medinan", 18),
        SurahInfo(50, "ق", "Qaf", "Meccan", 45),
        SurahInfo(51, "الذاريات", "Adh-Dhariyat", "Meccan", 60),
        SurahInfo(52, "الطور", "At-Tur", "Meccan", 49),
        SurahInfo(53, "النجم", "An-Najm", "Meccan", 62),
        SurahInfo(54, "القمر", "Al-Qamar", "Meccan", 55),
        SurahInfo(55, "الرحمن", "Ar-Rahman", "Medinan", 78),
        SurahInfo(56, "الواقعة", "Al-Waqi'a", "Meccan", 96),
        SurahInfo(57, "الحديد", "Al-Hadid", "Medinan", 29),
        SurahInfo(58, "المجادلة", "Al-Mujadila", "Medinan", 22),
        SurahInfo(59, "الحشر", "Al-Hashr", "Medinan", 24),
        SurahInfo(60, "الممتحنة", "Al-Mumtahina", "Medinan", 13),
        SurahInfo(61, "الصف", "As-Saff", "Medinan", 14),
        SurahInfo(62, "الجمعة", "Al-Jumu'a", "Medinan", 11),
        SurahInfo(63, "المنافقون", "Al-Munafiqun", "Medinan", 11),
        SurahInfo(64, "التغابن", "At-Taghabun", "Medinan", 18),
        SurahInfo(65, "الطلاق", "At-Talaq", "Medinan", 12),
        SurahInfo(66, "التحريم", "At-Tahrim", "Medinan", 12),
        SurahInfo(67, "الملك", "Al-Mulk", "Meccan", 30),
        SurahInfo(68, "القلم", "Al-Qalam", "Meccan", 52),
        SurahInfo(69, "الحاقة", "Al-Haqqa", "Meccan", 52),
        SurahInfo(70, "المعارج", "Al-Ma'arij", "Meccan", 44),
        SurahInfo(71, "نوح", "Nuh", "Meccan", 28),
        SurahInfo(72, "الجن", "Al-Jinn", "Meccan", 28),
        SurahInfo(73, "المزمل", "Al-Muzzammil", "Meccan", 20),
        SurahInfo(74, "المدثر", "Al-Muddathir", "Meccan", 56),
        SurahInfo(75, "القيامة", "Al-Qiyama", "Meccan", 40),
        SurahInfo(76, "الإنسان", "Al-Insan", "Medinan", 31),
        SurahInfo(77, "المرسلات", "Al-Mursalat", "Meccan", 50),
        SurahInfo(78, "النبأ", "An-Naba", "Meccan", 40),
        SurahInfo(79, "النازعات", "An-Nazi'at", "Meccan", 46),
        SurahInfo(80, "عبس", "Abasa", "Meccan", 42),
        SurahInfo(81, "التكوير", "At-Takwir", "Meccan", 29),
        SurahInfo(82, "الانفطار", "Al-Infitar", "Meccan", 19),
        SurahInfo(83, "المطففين", "Al-Mutaffifin", "Meccan", 36),
        SurahInfo(84, "الانشقاق", "Al-Inshiqaq", "Meccan", 25),
        SurahInfo(85, "البروج", "Al-Buruj", "Meccan", 22),
        SurahInfo(86, "الطارق", "At-Tariq", "Meccan", 17),
        SurahInfo(87, "الأعلى", "Al-A'la", "Meccan", 19),
        SurahInfo(88, "الغاشية", "Al-Ghashiya", "Meccan", 26),
        SurahInfo(89, "الفجر", "Al-Fajr", "Meccan", 30),
        SurahInfo(90, "البلد", "Al-Balad", "Meccan", 20),
        SurahInfo(91, "الشمس", "Ash-Shams", "Meccan", 15),
        SurahInfo(92, "الليل", "Al-Layl", "Meccan", 21),
        SurahInfo(93, "الضحى", "Ad-Duha", "Meccan", 11),
        SurahInfo(94, "الشرح", "Ash-Sharh", "Meccan", 8),
        SurahInfo(95, "التين", "At-Tin", "Meccan", 8),
        SurahInfo(96, "العلق", "Al-Alaq", "Meccan", 19),
        SurahInfo(97, "القدر", "Al-Qadr", "Meccan", 5),
        SurahInfo(98, "البينة", "Al-Bayyina", "Medinan", 8),
        SurahInfo(99, "الزلزلة", "Az-Zalzala", "Medinan", 8),
        SurahInfo(100, "العاديات", "Al-Adiyat", "Meccan", 11),
        SurahInfo(101, "القارعة", "Al-Qari'a", "Meccan", 11),
        SurahInfo(102, "التكاثر", "At-Takathur", "Meccan", 8),
        SurahInfo(103, "العصر", "Al-Asr", "Meccan", 3),
        SurahInfo(104, "الهمزة", "Al-Humaza", "Meccan", 9),
        SurahInfo(105, "الفيل", "Al-Fil", "Meccan", 5),
        SurahInfo(106, "قريش", "Quraysh", "Meccan", 4),
        SurahInfo(107, "الماعون", "Al-Ma'un", "Meccan", 7),
        SurahInfo(108, "الكوثر", "Al-Kawthar", "Meccan", 3),
        SurahInfo(109, "الكافرون", "Al-Kafirun", "Meccan", 6),
        SurahInfo(110, "النصر", "An-Nasr", "Medinan", 3),
        SurahInfo(111, "المسد", "Al-Masad", "Meccan", 5),
        SurahInfo(112, "الإخلاص", "Al-Ikhlas", "Meccan", 4),
        SurahInfo(113, "الفلق", "Al-Falaq", "Meccan", 5),
        SurahInfo(114, "الناس", "An-Nas", "Meccan", 6)
    )

    fun get(surahNumber: Int): SurahInfo? = all.getOrNull(surahNumber - 1)
}
